training_name = "test_misc"

[docker]
docker_image = "test_misc:latest" # docker image name 
cpu_limit = 1                     # Core
memory_limit = 64                 # MB
disk_limit = 256                  # MB
privileged = false
port = 80

[flag]
is_dynamic = false
static_flag = "flag{Y0u_F0und_ME!}" # static
is_nc = false
